### ISSUE TITLE
SensorAlarm Payload

### ISSUE THREAD

**Issue by boolemancer** [HclX/WyzeSensePy#1]
I found your blog posts while I was working on solving the same problem, and since I didn't see it here already, I figured I'd share what I found about the SensorAlarm payload for the contact/motion sensor.

```
8 bytes: big endian timestamp in milliseconds
1 byte:  sensor flags?, 0xa2 for both contact and motion sensor
8 bytes: sensor MAC
1 byte:  sensor type
1 byte:  unknown
1 byte:  remaining battery percentage
1 byte:  unknown, referred to as p1329
1 byte:  unknown
1 byte:  binary sensor state (1: opened/motion detected, 0: closed/no motion detected)
2 bytes: big endian counter for when the sensor is triggered
1 byte:  signal strength, presumably something like absolute value of RSSI (lower is better)
```

Hope it's helpful.

EDIT: What I had before as 'sensor index' actually looks like the 'sensor type', probably the same value as in the response to dongle_sensor_Random_date_send, where it maps to the dongle_sensor_mode string (DWS3U for contact sensor, PIR3U for the motion sensor)

**Comment by GeorgeHahn** [comment]
I believe the byte before battery percentage is signal strength ([notes](https://github.com/GeorgeHahn/stunning-broccoli/blob/master/serial-data/all-joins.txt#L97)). USB traces and in-progress Rust implementation here: [GeorgeHahn/stunning-broccoli](https://github.com/GeorgeHahn/stunning-broccoli/).

**Comment by HclX** [comment]
thanks for the information, i've incorporated this into the python code.
