### ISSUE TITLE
Quick question: Do you think this repo / integration is stable? It's not.

### ISSUE THREAD

**Issue by RoldyBuffalo** [HclX/WyzeSensePy#15]
64 open issue tickets currently on the [Wyze Sense repo](https://github.com/kevinvincent/ha-wyzesense)

All of them revolving around a faulty api, bad code snippets being sent to the hub, broken sensors, hung hassos, everything revolving around this very shoddy api implementation.

I'm all for giving credit where credit is due, but the amount of issues I've seen and experienced myself, along with 100's of others, is too high to not mention.

If you would like me to NOT link this repo on that repo's tickets for further inspection (essentially, the way I see it, if they know that this repo even existed, they would have 2x as many tickets here, as there) I highly suggest you either close the project completely and release us from this nonsense of having broken implementations that barely work, or take a significant amount of time testing this python code, along with that repo's code, and figure out some of these very repetitive tickets.

It's all the same issues, you have said in other tickets on this repo that these issues where "fixed" but I fail to see the solution being as easy as one PR which very obviously only increased the number of new issue tickets made .

Fix it, or I blow the lid off this and start having people submit their issue tickets here. I'm beyond tired of this.

**Comment by IIAIronWolf** [comment]
This is not the wysesene repo. wysense uses some of this code. Why not contribute code if it bothers you so much? This was given to us for free..

**Comment by RoldyBuffalo** [comment]
The Wyze Sense repo is based on this python code. It's a failure from multiple angles. Furthermore, I have contributed code, to the wyze sense repo. The repo / component that highly relies on this python code to function is broken. Hope this clears up your misunderstanding.

**Comment by IIAIronWolf** [comment]
No misunderstanding here, bud. Ask for write access and fix it for us, for free. ;)
