### ISSUE TITLE
Signal information if needed

### ISSUE THREAD

**Issue by allordacia** [HclX/WyzeSensePy#2]
I have also been working on doing this only I took the route of intercepting the data from the signals as they were being sent back to the hub. I dont know if I have anything of value for your project but If you would like to see any of the information I have with regards to how the signals are sent/received I can provide them!

Good luck!

**Comment by HclX** [comment]
Sure thing. Reversing the firmware of the sensor and gateway is definitely on my radar. Knowing signals being transferred between sensor node and hub will be very useful. Please keep me posted for any of your findings.
